# Generated by Django 4.2 on 2025-01-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_count', models.IntegerField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='timetables.timetable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
