# Generated by Django 4.2 on 2025-01-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
